name: Deploy React to AWS EC2

on:
   push:
      branches:
         - master

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Install Dependencies & Build
           run: |
              npm install
              npm run build

         - name: Log in to Docker Hub
           run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

         - name: Build & Push Docker Image
           run: |
              docker build -t vinay41/react-app .
              docker tag vinay41/react-app:latest vinay41/react-app:latest
              docker push vinay41/react-app:latest

         - name: Setup SSH Key # Fix: Add SSH key for EC2
           run: |
              echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
              chmod 600 private_key.pem

         - name: Deploy to AWS EC2
           run: |
              ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
              cd /home/ubuntu/docker-app
              docker-compose pull
              docker-compose up -d
              EOF
